### ISSUE TITLE
Remove Type Hints from Repository, Search, Filter, and Sort

### ISSUE THREAD

**Issue by cole-flexsim** [Gustavinho/laravel-views#122]
the repository function is type hinted to require a Builder instance which makes it so relations do not work. 

For example if I wanted to load posts on the currently logged in user like so:

```php
public function repository() {
    return Auth::user()->posts();
}
```

There is an exception thrown. 

If you only care about supporting php 8.0 and above then you can still type hint all of the related functions and just make the type hints Builder|Relation

or to keep backwards compatibility remove the type hints and manually do some type checking and exception throwing

**Comment by Gustavinho** [comment]
Hi @cole-flexsim sorry for the very late response, I've been testing this approach without the type hint to evaluate the effort for us to change our current implementations, my only concern is that we should have to change the definition of all of our filters as an upgrade process since this query that is returned in the `repository` function is used for everything, filters, and search, there is a workaround for this cases and it would be creating the query from the `Post` model, something like 
```php
public function repository() {
    return Post::where('user_id', Auth::user()->id);
}
```
