### ISSUE TITLE
Cannot sort by relation column

### ISSUE THREAD

**Issue by samankassou** [Gustavinho/laravel-views#130]
I tried to do this in the `headers` method:
```php
Header::title('Author')->sortBy('author.name'),
...
```
but it show me this error:
```bash
Column not found: Unknown column 'author.name' in 'order clause'
```
I have `author` relation in my `Post` model

**Comment by Gustavinho** [comment]
Hi @samankassou, yeah unfortunately it doesn't have support to sort by a relation column, I could add this to the roadmap for next releases

**Comment by samankassou** [comment]
Thanks, You are making a good job

**Comment by Razziel06** [comment]
Hi @samankassou & @Gustavinho . I realise that this is an old issue, but I just started using this and found a solution for sorting a table by a relation column. I also got eager loading to work, so that the number of queries is reduced.

In my example I have a `Workorder` model that has a "belongs to" relationship with a `Product` model.

Instead of using the I'm using the `repository()` method to return a query:
```
protected $model = Workorder::class;

public function repository(): Builder
    {
        return Workorder::query()
            ->with("product") // Relationship defined in the Workorder model
            ->join("products", "workorders.product_id", "=", "products.id") // Joining the products table with the workorders table
            ->select("workorders.*", "products.name"); // Selecting all of the fields to include in the table
    }
```

The `headers()` method can then include the proper column name for the product with the `sortBy()` method:
```
public function headers(): array
    {
        return [
            // ...

            Header::title("Job")->sortBy("job_number"),
            Header::title("Product Name")->sortBy("products.name"),

            // ...
        ];
    }
```

The `row()` method remains the same as you would usually do it:
```
public function row($model): array
    {
        return [
            // ...

            $model->job_number,
            $model->product->name

            // ...
        ];
    }
```

Hope this helps anybody in the future! :)

**Comment by Gustavinho** [comment]
Thanks @Razziel06, this is awesome, it'll be so helpful 

I'll close this issue btw
