### ISSUE TITLE
Make individual parts of the views customizable 

### ISSUE THREAD

**Issue by cole-flexsim** [Gustavinho/laravel-views#133]
Hey @Gustavinho this is an idea I have been working on for a little bit. I want to be able to customize certain parts of my laravel views pages (such as the action buttons) but there isn't an easy way to do so aside from overriding the main view component and then customizing the pieces I need to. 

I came up with a solution so that on a per view basis a user of this package can customize pieces of that view without having to override any of the package blade files. I want to get your feedback on this implementation before I submit a pull request because I image this will require changing a lot of files.

This is an example with having a custom actions dropdown on a detail view class:

Old components.actions.responsive.blade.php:
```html
@props(['actions' => [], 'model' => null])

<div>
  @if (count($actions))
    {{-- Mobile actions dropdown --}}
    <div class="lg:hidden text-right relative">
      <x-lv-actions.drop-down :actions="$actions" :model="$model" />
    </div>

    {{-- Desktop action buttons --}}
    <div class="hidden lg:flex justify-items-end">
        <x-lv-actions.icon :actions="$actions" :model="$model" />
    </div>
  @endif
</div>
```

New responseive.blade.php
```html
@props(['actions' => [], 'model' => null])

<div>
  @if (count($actions))
    {{-- Mobile actions dropdown --}}
    <div class="lg:hidden text-right relative">
       // I changed this line
      <x-dynamic-component :component="$this->getComponent('actionDropdownComponent')" :actions="$actions" :model="$model"/>
    </div>

    {{-- Desktop action buttons --}}
    <div class="hidden lg:flex justify-items-end">
        <x-lv-actions.icon :actions="$actions" :model="$model" />
    </div>
  @endif
</div>
```

The getComponent function is defined on the abstract View class:
```php
<?php

namespace LaravelViews\Views;

use Livewire\Component;
use Livewire\Exceptions\PropertyNotFoundException;

abstract class View extends Component
{
   ...

    public function getComponent($component)
    {
        try {
            return $this->$component;
        } catch (PropertyNotFoundException $e) {
            return $this->defaultComponents[$component];
        }
    }
}
```

and then each other view class defines the defaultComponents property
```php
<?php

namespace LaravelViews\Views;

class DetailView extends View
{
    ...

    protected $defaultComponents = [
        'actionDropdownComponent' => 'lv-actions.drop-down'
    ];

    ...
}
```

Then lets say a user wants a custom dropdown on their DetailView. All they have to do is create their blade file and then define a $actionDropdownComponent property or getActionDropdownComponentProperty method on their DetailView class:
```php
<?php

namespace App\Http\Livewire\DetailView;

use App\Models\User;
use LaravelViews\Facades\UI;
use LaravelViews\Views\DetailView;

class UserDetailView extends DetailView
{
    ...

   $actionDropdownComponent  = 'my-user-detail-view.actions.drop-down';

   or

   public function getActionDropdownComponentProperty() {
      return 'my-user-detail-view.actions.drop-down';
   }
   ...
}
```

I imagine this same kind of implementation can be applied to action/filter classes to allow customization of those blade components on a per item basis as well. 

Let me know your thoughts on this implementation. I will most likely make the getComponent function part of a trait so that it can be applied to the view class as well as the action and filter classes

**Comment by Gustavinho** [comment]
Hi @cole-flexsim , this is a very good idea, one of my biggest concerns about releasing a new version is that if the internal components have changed for some new features, and we have published and changed the internal blade components in our project we should either replace the components we have customized or missing the new changes on those components, even leading into an error, this approach of yours could avoid publishing the internal components just to customize a button for example, 

I have a couple of comments.
1. This should apply for customizing the internal card and list items right? the package already has this kind of implementation for only these two components.
2. As far as i remember, the `<x-dynamic-component />` is only available for Laravel 8, this package is supporting Laravel 7 so we couldn't use it yet, I have an internal `x-lv-dynamic-component` for internal usage that is bypassing the `AnonymousComponent` class, but I'm not sure if that component will work out.
3. Should the documentation have all the potential methods and props to be defined?  like `getActionDropdownComponentProperty` so we can (as users of the package) know the components to be customized without inspecting the code, including the props so we can build our own components with the same base features.

I really like your idea overall, it could give the package more flexibility about components customization, I would really like to avoid publishing the internal components as much as possible because of the braking changes, and this could help to solve it somehow.

**Comment by cole-flexsim** [comment]
@Gustavinho Thanks for the reply. I'm glad you also like this idea. I started working on this implementation yesterday so I have a better idea of how this will work now. In answer to your questions above:

1. Yes I think that I will apply the same kind of implementation to the internal card items and list items. That way the whole package is consistent. I think it would be nice for the users to be have access to a command that would allow them to publish a specific blade component from the package to their laravel project. I think this would make the users less likely to publish all the blade components and instead just publish the ones they need to modify for their project.   
   
   I am planning on adding the defaultComponents array to the laravel-views config file so that if a user wants to override a blade component for their whole laravel project they will be able to do so. 
2.  You are right the `<x-dynamic-component />` is only available in laravel 8 and higher. I have two ways I could go forward:
    1. I could swap all of the `<x-dynamic-component />`'s for `@component` directives. This directive has been around since laravel 5.4 so we would have no issues supporting the dynamic components this way.
    1.  The second option is to turn this feature into the beginning of laravel-views v3.0. This functionality will be a major change to the project anyway so it makes sense to me to make this update part of a whole new version. If we go this route we could decide that from laravel-views v3.0 and onward we only support laravel 8 and up. This would fit with this version of the package releasing later this year just before laravel 9 comes out in January. 
3.  I definitely think that all of this functionality should become part of the documentation. My current train of thought is to turn the "live examples" site into the main source of documentation for the project since the laravel-views project keeps growing in functionality. I think this will make the documentation easier to maintain than trying to keep everything in the readme.md files.

Let me know your thoughts. I will try to get my initial pull request up by then end of the day

**Comment by Gustavinho** [comment]
Hi @cole-flexsim, sorry for the late respnse, I really liked most of your ideas, I liked having the default components on the config file, actually, I don't like to have the customization of the color on it, it is more a theme thing than a config. 

About releasing a v3.0 I was actually thinking to do that when Laravel 9 is released, I'm just still thinking to release some other views on v2.

About the docs, I tried to move it to the live examples site some time ago but I had to drop it because of a lack of time but I really liked that idea, I will give it another shot

In the meantime I will add these to the current backlog
- Have a command to publish specific blade components, not just of all of them

**Comment by cole-flexsim** [comment]
No worries @Gustavinho, I have made a lot of progress on getting this set up in the project. Right now I have the back end functionality set up and working. I am now working through the various views and blade templates merging some together and splitting others apart. I'm currently up to changes in 40 different files and counting.

I apologize in advance that the pull request will not be easy to work through. 

If v3.0 of the package is scheduled for after laravel 9 is released that's fine with me. I think the number of changes in this feature make sense to be part of a major release. 

If its okay with you I'll submit this pull request as a v3.0 branch and then I'll continue to keep the v3.0 branch up to date with the changes you make on v2

**Comment by Gustavinho** [comment]
Same page then
