### ISSUE TITLE
Sorting on Table

### ISSUE THREAD

**Issue by fawzanm** [Gustavinho/laravel-views#19]
Hi, 

I think the ability to sort the columns is a must-have feature for a table. I have ported a simple solution for my project which I believe will be a good PR. I need your feedback on how best I can port it to the package. 

This is my current approach. 

1. I have added a custom `Sortable` trait
2. I am passing the sort related data to the table on `table-view.blade.php` 
3. Modified the `<th>` in the published `table.blade.php` file
```


trait Sortable
{

    public string $sortKey = 'id';

    public bool $sortOrder = false;

    public function sort($key): void
    {
        if ($key === $this->sortKey) {
            $this->sortOrder = !$this->sortOrder;
        } else {
            $this->sortKey = $key;
            $this->sortOrder = false;
        }

    }

}
```

```
       @component('laravel-views::components.table', [
              'headers' => $headers,
              'actionsByRow' => $actionsByRow,
              'items' => $items,
              'view' => $view,
              'sortBy' => $sortBy,
              'sortKey' => $sortKey,
              'sortOrder' => $sortOrder
            ])
```

```
   <th class="px-3 py-3">

                @php($lowerHeader = strtolower($header))

                @if(in_array(strtolower($header), $sortBy, true))
                    <span style="cursor: pointer;" wire:click="sort('{{$lowerHeader}}')">
                        {{$header}}
                        @if($sortKey !== $lowerHeader)
                            <i class="text-muted fas fa-sort"></i>
                        @elseif($sortOrder)
                            <i class="text-muted fas fa-sort-up"></i>
                        @else
                            <i class="text-muted fas fa-sort-down"></i>
                        @endif

                    </span>
                @else
                    {{ $header }}
                @endif
            </th>
```

To use the sort, all we have to do is add this property to our table. 

```
    public array $sortBy = [ 'id', 'name' ];

```

Let me know what you think, I would be more than happy to send a PR with the modifications.

**Comment by Gustavinho** [comment]
Yes, same as you asked for the confirmation message, this is going to be a feature for `v1.2`, I like your approach but I'll say some recommendations

1. I like the `trait` approach but the search and filter features are using contracts/interfaces, so I would do the `sortable`  trait as an `interface` instead, this way the dev will be able to write its own implementation (not documented yet)
3. Maybe instead of use separate variables for sort order and key, it could be an array, plus the  `sortOrder` value might be 'desc' and 'asc', just another approach
2. I wouldn't add `@php($lowerHeader = strtolower($header))` on the blade file, I think I would create a helper for that or a method inside the table class, but despite that, there is a problem binding the header title with the sortable field, because the header title is open to be whatever we want, that is the tricky part of this feature.

I'm gonna add a contribution guide and maybe a roadmap to the documentation, I think it would be helpful
Thanks so much for taking your time with these issues and PR's

**Comment by fawzanm** [comment]
That's a great tip @Gustavinho. Looking forward to v1.2. I really enjoy using this package and I will send useful PRs continuously.

**Comment by fawzanm** [comment]
@Gustavinho do you have to work on this anytime soon or shall I give it a try and send a PR?

**Comment by Gustavinho** [comment]
> @Gustavinho do you have any plans to work on this anytime soon or shall I give it a try and send a PR?

Hello, yes I was planning to work on the `v1.1` this weekend, however, feel free to send a PR for this feature, there are a lot of features to include and if you are able to collaborate with this one that would be so helpful, just send it to `release-1.1.0` branch

**Comment by fawzanm** [comment]
@Gustavinho okay, I will try and send a PR within this week.
